version: "3.2"
services:
    database:
        image: "mysql"
        ports:
            - 3306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: "hamzeh1378"
            MYSQL_USER: hamzeh
            MYSQL_PASSWORD: hamzeh1378
            MYSQL_DATABASE: blog
        volumes: 
            - "./.mysql-data/db:/var/lib/mysql"                         
volumes:
    blogDbData: